### ISSUE TITLE
problem packages for e3sm-unified 1.2.6

### ISSUE THREAD

**Issue by xylar** [E3SM-Project/e3sm-unified#51]
A number of packages are giving me trouble for e3sm-unified 1.2.6:
- [x] `output_viewer` - no `conda-forge` build for python 3.7.  Need this PR merged: https://github.com/conda-forge/output_viewer-feedstock/pull/4.  This is also a dependency of `e3sm_diags`, which is a dependency of `processflow`, so neither of those can be included without this fix.
- [x] `thermo` - conflicting package in `conda-forge` channel is taking priority.  This package probably needs to be renamed.  Issue here: https://github.com/CDAT/thermo/issues/11.  Dependency of `cdat`, so that also currently cannot be included. Moved to `vcsaddons` by @doutriaux1, thanks!
- [x] `globus-cli` - dependency `jmespath=0.9.2` not build for python 3.7.  Pull request in here: https://github.com/conda-forge/jmespath-feedstock/pull/7. Issue requesting an update in dependency here: https://github.com/globus/globus-cli/issues/461
- [x] `cdp` - built incorrectly with pinned python.  Fixed via: https://github.com/conda-forge/cdp-feedstock/pull/7
- [x] `processflow` - depends on `globus-cli 1.1.2` and `globus-sdk 1.1.1`, neither of which is available on conda-forge.  With strict channel priority (needed to make builds work with the latest conda), these versions from the `e3sm` channel are no longer available to `e3sm-unified`. Here's the build of `globus-sdk 1.1.1`: https://github.com/conda-forge/globus-sdk-feedstock/pull/8 and of `globus-cli 1.1.2`: https://github.com/conda-forge/globus-cli-feedstock/pull/6
- [x] `ncl` vs. `basemap` - `ncl` is a dependency of `processflow`; `basemap` is a dependency of `ilamb`, `mpas-analysis` and `cdat`.  `ncl` is not compatible with `pyproj>=1.9.6,<2.0.0` and `proj4>=5.2.0,<6.0.0` for any build with `hdf5=1.10.5`.  `basemap` has not yet been released with a version compatible with `pyproj>=2.0.0` and `proj4>=6.0.0`.  A request was made over a year ago to have a new release of `basemap` with no luck: https://github.com/matplotlib/basemap/issues/405.  This issue was addressed with a new release of `processflow` without the `ncl` dependency.  Users will need to load the local system version manually.
- [x] `hdf5=1.10.5` - Not a show-stopper but a pain is the dependence of various packages on the `cdat/label/v81` channel on `hdf5=1.10.4`, whereas conda-forge packages are being built with `hdf5=1.10.5`.  I had to rebuild `mpas_tools=0.0.3` and `nco=4.8.1` with this older version.  A request to have `cdat/label/v81` packages rebuilt with the more recent hdf5 is here: https://github.com/CDAT/cdat/issues/2234

**Update**: I tried using `hdf5=1.10.5` this morning and it "just worked"!  But there's a remaining incompatibility between `basemap` and `ncl` that I don't have a good solution for.
